CREATE USER IF NOT EXISTS 'sofiamishell2003'@'%' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON blog_db.* TO 'sofiamishell2003'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS cetaceos (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR (255) NOT NULL,
	description TEXT NOT NULL,
	family VARCHAR(100),
	diet VARCHAR (100),
	funfact VARCHAR (255)
);
